// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"videoweb/config"
	"videoweb/database/DB/dao"
	"videoweb/database/cache"
)

func main() {
	h := server.Default()
	dao.InitDB()
	config.InitMinIoClient()
	cache.InitRedis()

	register(h)
	h.Spin()
}
